#!/bin/bash
dirname=$(dirname "$0")
flagfile="$dirname/relaunch"

touch "$flagfile"
while [ -e "$dirname/relaunch" ]; do
   rm -f "$flagfile"
   "$dirname/polebot" --config-file config
   sleep 2
done

echo "monitor exiting"
